### ISSUE TITLE
Getting {"type": "dismiss"}  in Browser Login 

### ISSUE THREAD

**Issue by Binary-Shade** [adrianhajdin/react_native-restate#1]
### Description
I'm encountering an issue with the `openAuthSessionAsync` method from `expo-web-browser` while integrating OAuth login using Appwrite in a React Native application. The problem is that after initiating the OAuth flow, the browser doesn't close, and the returned result always has the type `dismiss`.

### Actual Behavior
- The browser does not close after the OAuth flow.
- The returned result always has the type `dismiss`.
- Logs:
  ```
  🚀 ~ login ~ browserResult: {"type": "dismiss"}
  (NOBRIDGE) ERROR  [Error: browser login failed]
  ```

### Additional Details
- Verified the `redirectUri` matches the OAuth provider's settings in the Appwrite console.
- Tested on both Android and iOS with the same behavior.
- Used a standalone build for testing (not Expo Go).
- Tried using `closeAuthSessionAsync()` without success.

### Relevant Code Snippet
```javascript
import { createURL } from 'expo-linking'

export const login = async () => {
    try {
        const redirectUri = createURL('/');
        const response = await account.createOAuth2Token(OAuthProvider.Google, redirectUri);

        if (!response) throw new Error("login failed in oauth provider!");

        const browserResult = await openAuthSessionAsync(response.toString(), redirectUri);
        console.log("Browser Result:", browserResult);

        if (browserResult.type !== 'success') throw new Error('Browser login failed');

        const url = new URL(browserResult.url);
        const secret = url.searchParams.get('secret');
        const userId = url.searchParams.get('userId');

        if (!secret || !userId) throw new Error('Failed to retrieve user ID or secret');

        const session = await account.createSession(userId, secret);
        console.log("Session created:", session);

        return session;
    } catch (error) {
        console.error(error);
        return false;
    }
};
```

**Comment by Karan-develops** [comment]
Bro in Line3 its  -->  const redirectUri = Linking.createURL("/");
Tell me if it solves the issue

**Comment by Binary-Shade** [comment]
you are the one who replied to my comment in youtube . Did this solution solves your issue ??

**Comment by Binary-Shade** [comment]
> ## Solution 1 ==> Bro in Line3 its --> const redirectUri = Linking.createURL("/");
> ## Solution 2 ==> Delete user from appwrite and Try Again.
> 
> Tell me if it solves the issue.

no :) its not working !

**Comment by Binary-Shade** [comment]
**switched to clerk auth system && closing this issue :(**

**Comment by Binary-Shade** [comment]
**switched to clerk auth system && closing this issue :(**

**Comment by darrenbutcher** [comment]
Hey was having the same issue with android (Expo Go). Actually this seems to be an issue that comes up with android since I found a few open expo issues. This was my fix after reading through some solutions: 

```js
    const browserResult = await openAuthSessionAsync(
      response.toString(),
      redirectUri,
      {
        showInRecents: true,
      }
    )
```
@Binary-Shade @Karan-develops maybe you can see if this works. For anyone else hope this helps.

According to doc's showInRecents is a specific option for android. As per the docs `A boolean determining whether browsed website should be shown as separate entry in Android recents/multitasking view.` The Default:
`false`

**Comment by getFrontend** [comment]
![Image](https://github.com/user-attachments/assets/637a79f9-28c8-479b-8cee-2201da5ae04e)

I think you forgot to set that setting on Appwrite Dashboard

**Comment by Binary-Shade** [comment]
> Hey was having the same issue with android (Expo Go). Actually this seems to be an issue that comes up with android since I found a few open expo issues. This was my fix after reading through some solutions:
> 
>     const browserResult = await openAuthSessionAsync(
>       response.toString(),
>       redirectUri,
>       {
>         showInRecents: true,
>       }
>     )
> 
> [@Binary-Shade](https://github.com/Binary-Shade) [@Karan-develops](https://github.com/Karan-develops) maybe you can see if this works. For anyone else hope this helps.
> 
> According to doc's showInRecents is a specific option for android. As per the docs `A boolean determining whether browsed website should be shown as separate entry in Android recents/multitasking view.` The Default: `false`

thanks 👍
